<?php
/**
 * SigningCeremonyApi
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SigniFlowConnect\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SigniFlowConnect\ApiException;
use SigniFlowConnect\Configuration;
use SigniFlowConnect\HeaderSelector;
use SigniFlowConnect\ObjectSerializer;

/**
 * SigningCeremonyApi Class Doc Comment
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SigningCeremonyApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation postMultipleSignersSigningCeremony
     *
     * Multiple Signers Signing Ceremony
     *
     * @param  string $content_type content_type (required)
     * @param  \SigniFlowConnect\Model\MultipleSignersSigningCeremonyRequest $multiple_signers_signing_ceremony_request ##### Multiple Signers Signing Ceremony Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SigniFlowConnect\Model\MultipleSignersSigningCeremonyResponse
     */
    public function postMultipleSignersSigningCeremony($content_type, $multiple_signers_signing_ceremony_request = null)
    {
        list($response) = $this->postMultipleSignersSigningCeremonyWithHttpInfo($content_type, $multiple_signers_signing_ceremony_request);
        return $response;
    }

    /**
     * Operation postMultipleSignersSigningCeremonyWithHttpInfo
     *
     * Multiple Signers Signing Ceremony
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\MultipleSignersSigningCeremonyRequest $multiple_signers_signing_ceremony_request ##### Multiple Signers Signing Ceremony Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SigniFlowConnect\Model\MultipleSignersSigningCeremonyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postMultipleSignersSigningCeremonyWithHttpInfo($content_type, $multiple_signers_signing_ceremony_request = null)
    {
        $request = $this->postMultipleSignersSigningCeremonyRequest($content_type, $multiple_signers_signing_ceremony_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\SigniFlowConnect\Model\MultipleSignersSigningCeremonyResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SigniFlowConnect\Model\MultipleSignersSigningCeremonyResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SigniFlowConnect\Model\MultipleSignersSigningCeremonyResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SigniFlowConnect\Model\MultipleSignersSigningCeremonyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postMultipleSignersSigningCeremonyAsync
     *
     * Multiple Signers Signing Ceremony
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\MultipleSignersSigningCeremonyRequest $multiple_signers_signing_ceremony_request ##### Multiple Signers Signing Ceremony Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postMultipleSignersSigningCeremonyAsync($content_type, $multiple_signers_signing_ceremony_request = null)
    {
        return $this->postMultipleSignersSigningCeremonyAsyncWithHttpInfo($content_type, $multiple_signers_signing_ceremony_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postMultipleSignersSigningCeremonyAsyncWithHttpInfo
     *
     * Multiple Signers Signing Ceremony
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\MultipleSignersSigningCeremonyRequest $multiple_signers_signing_ceremony_request ##### Multiple Signers Signing Ceremony Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postMultipleSignersSigningCeremonyAsyncWithHttpInfo($content_type, $multiple_signers_signing_ceremony_request = null)
    {
        $returnType = '\SigniFlowConnect\Model\MultipleSignersSigningCeremonyResponse';
        $request = $this->postMultipleSignersSigningCeremonyRequest($content_type, $multiple_signers_signing_ceremony_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postMultipleSignersSigningCeremony'
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\MultipleSignersSigningCeremonyRequest $multiple_signers_signing_ceremony_request ##### Multiple Signers Signing Ceremony Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postMultipleSignersSigningCeremonyRequest($content_type, $multiple_signers_signing_ceremony_request = null)
    {
        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling postMultipleSignersSigningCeremony'
            );
        }

        $resourcePath = '/MultipleSignersSigningCeremony';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($multiple_signers_signing_ceremony_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($multiple_signers_signing_ceremony_request));
            } else {
                $httpBody = $multiple_signers_signing_ceremony_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postSigningCeremonyV2
     *
     * Signing Ceremony V2
     *
     * @param  string $content_type content_type (required)
     * @param  \SigniFlowConnect\Model\SigningCeremonyV2Request $signing_ceremony_v2_request ##### Signing Ceremony V2 Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SigniFlowConnect\Model\SigningCeremonyV2Response
     */
    public function postSigningCeremonyV2($content_type, $signing_ceremony_v2_request = null)
    {
        list($response) = $this->postSigningCeremonyV2WithHttpInfo($content_type, $signing_ceremony_v2_request);
        return $response;
    }

    /**
     * Operation postSigningCeremonyV2WithHttpInfo
     *
     * Signing Ceremony V2
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\SigningCeremonyV2Request $signing_ceremony_v2_request ##### Signing Ceremony V2 Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SigniFlowConnect\Model\SigningCeremonyV2Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function postSigningCeremonyV2WithHttpInfo($content_type, $signing_ceremony_v2_request = null)
    {
        $request = $this->postSigningCeremonyV2Request($content_type, $signing_ceremony_v2_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\SigniFlowConnect\Model\SigningCeremonyV2Response' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SigniFlowConnect\Model\SigningCeremonyV2Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SigniFlowConnect\Model\SigningCeremonyV2Response';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SigniFlowConnect\Model\SigningCeremonyV2Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postSigningCeremonyV2Async
     *
     * Signing Ceremony V2
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\SigningCeremonyV2Request $signing_ceremony_v2_request ##### Signing Ceremony V2 Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postSigningCeremonyV2Async($content_type, $signing_ceremony_v2_request = null)
    {
        return $this->postSigningCeremonyV2AsyncWithHttpInfo($content_type, $signing_ceremony_v2_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postSigningCeremonyV2AsyncWithHttpInfo
     *
     * Signing Ceremony V2
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\SigningCeremonyV2Request $signing_ceremony_v2_request ##### Signing Ceremony V2 Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postSigningCeremonyV2AsyncWithHttpInfo($content_type, $signing_ceremony_v2_request = null)
    {
        $returnType = '\SigniFlowConnect\Model\SigningCeremonyV2Response';
        $request = $this->postSigningCeremonyV2Request($content_type, $signing_ceremony_v2_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postSigningCeremonyV2'
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\SigningCeremonyV2Request $signing_ceremony_v2_request ##### Signing Ceremony V2 Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postSigningCeremonyV2Request($content_type, $signing_ceremony_v2_request = null)
    {
        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling postSigningCeremonyV2'
            );
        }

        $resourcePath = '/SigningCeremonyV2';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($signing_ceremony_v2_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($signing_ceremony_v2_request));
            } else {
                $httpBody = $signing_ceremony_v2_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
