<?php
/**
 * TemplatesApi
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SigniFlowConnect\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SigniFlowConnect\ApiException;
use SigniFlowConnect\Configuration;
use SigniFlowConnect\HeaderSelector;
use SigniFlowConnect\ObjectSerializer;

/**
 * TemplatesApi Class Doc Comment
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TemplatesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation postApplyPrepperTemplate
     *
     * Apply a Prepper template
     *
     * @param  string $content_type content_type (required)
     * @param  \SigniFlowConnect\Model\ApplyPrepperTemplateRequest $apply_prepper_template_request ##### Apply A Prepper Template Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SigniFlowConnect\Model\ApplyPrepperTemplateResponse
     */
    public function postApplyPrepperTemplate($content_type, $apply_prepper_template_request = null)
    {
        list($response) = $this->postApplyPrepperTemplateWithHttpInfo($content_type, $apply_prepper_template_request);
        return $response;
    }

    /**
     * Operation postApplyPrepperTemplateWithHttpInfo
     *
     * Apply a Prepper template
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\ApplyPrepperTemplateRequest $apply_prepper_template_request ##### Apply A Prepper Template Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SigniFlowConnect\Model\ApplyPrepperTemplateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postApplyPrepperTemplateWithHttpInfo($content_type, $apply_prepper_template_request = null)
    {
        $request = $this->postApplyPrepperTemplateRequest($content_type, $apply_prepper_template_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\SigniFlowConnect\Model\ApplyPrepperTemplateResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SigniFlowConnect\Model\ApplyPrepperTemplateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SigniFlowConnect\Model\ApplyPrepperTemplateResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SigniFlowConnect\Model\ApplyPrepperTemplateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postApplyPrepperTemplateAsync
     *
     * Apply a Prepper template
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\ApplyPrepperTemplateRequest $apply_prepper_template_request ##### Apply A Prepper Template Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postApplyPrepperTemplateAsync($content_type, $apply_prepper_template_request = null)
    {
        return $this->postApplyPrepperTemplateAsyncWithHttpInfo($content_type, $apply_prepper_template_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postApplyPrepperTemplateAsyncWithHttpInfo
     *
     * Apply a Prepper template
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\ApplyPrepperTemplateRequest $apply_prepper_template_request ##### Apply A Prepper Template Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postApplyPrepperTemplateAsyncWithHttpInfo($content_type, $apply_prepper_template_request = null)
    {
        $returnType = '\SigniFlowConnect\Model\ApplyPrepperTemplateResponse';
        $request = $this->postApplyPrepperTemplateRequest($content_type, $apply_prepper_template_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postApplyPrepperTemplate'
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\ApplyPrepperTemplateRequest $apply_prepper_template_request ##### Apply A Prepper Template Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postApplyPrepperTemplateRequest($content_type, $apply_prepper_template_request = null)
    {
        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling postApplyPrepperTemplate'
            );
        }

        $resourcePath = '/ApplyPrepperTemplate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($apply_prepper_template_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($apply_prepper_template_request));
            } else {
                $httpBody = $apply_prepper_template_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postGetDocumentTagFieldBoxPosition
     *
     * Get Document Tag Field Box Position
     *
     * @param  string $content_type content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionRequest $get_document_tag_field_box_position_request ##### Get Document Tag Field Box Position Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionResponse
     */
    public function postGetDocumentTagFieldBoxPosition($content_type, $get_document_tag_field_box_position_request = null)
    {
        list($response) = $this->postGetDocumentTagFieldBoxPositionWithHttpInfo($content_type, $get_document_tag_field_box_position_request);
        return $response;
    }

    /**
     * Operation postGetDocumentTagFieldBoxPositionWithHttpInfo
     *
     * Get Document Tag Field Box Position
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionRequest $get_document_tag_field_box_position_request ##### Get Document Tag Field Box Position Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postGetDocumentTagFieldBoxPositionWithHttpInfo($content_type, $get_document_tag_field_box_position_request = null)
    {
        $request = $this->postGetDocumentTagFieldBoxPositionRequest($content_type, $get_document_tag_field_box_position_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postGetDocumentTagFieldBoxPositionAsync
     *
     * Get Document Tag Field Box Position
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionRequest $get_document_tag_field_box_position_request ##### Get Document Tag Field Box Position Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGetDocumentTagFieldBoxPositionAsync($content_type, $get_document_tag_field_box_position_request = null)
    {
        return $this->postGetDocumentTagFieldBoxPositionAsyncWithHttpInfo($content_type, $get_document_tag_field_box_position_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postGetDocumentTagFieldBoxPositionAsyncWithHttpInfo
     *
     * Get Document Tag Field Box Position
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionRequest $get_document_tag_field_box_position_request ##### Get Document Tag Field Box Position Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGetDocumentTagFieldBoxPositionAsyncWithHttpInfo($content_type, $get_document_tag_field_box_position_request = null)
    {
        $returnType = '\SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionResponse';
        $request = $this->postGetDocumentTagFieldBoxPositionRequest($content_type, $get_document_tag_field_box_position_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postGetDocumentTagFieldBoxPosition'
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldBoxPositionRequest $get_document_tag_field_box_position_request ##### Get Document Tag Field Box Position Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postGetDocumentTagFieldBoxPositionRequest($content_type, $get_document_tag_field_box_position_request = null)
    {
        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling postGetDocumentTagFieldBoxPosition'
            );
        }

        $resourcePath = '/GetDocumentTagFieldBoxPosition';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($get_document_tag_field_box_position_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($get_document_tag_field_box_position_request));
            } else {
                $httpBody = $get_document_tag_field_box_position_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postGetDocumentTagFieldPosition
     *
     * Get Document Tag Field Position
     *
     * @param  string $content_type content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldPositionRequest $get_document_tag_field_position_request ##### Get Document Tag Field Position Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SigniFlowConnect\Model\GetDocumentTagFieldPositionResponse
     */
    public function postGetDocumentTagFieldPosition($content_type, $get_document_tag_field_position_request = null)
    {
        list($response) = $this->postGetDocumentTagFieldPositionWithHttpInfo($content_type, $get_document_tag_field_position_request);
        return $response;
    }

    /**
     * Operation postGetDocumentTagFieldPositionWithHttpInfo
     *
     * Get Document Tag Field Position
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldPositionRequest $get_document_tag_field_position_request ##### Get Document Tag Field Position Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SigniFlowConnect\Model\GetDocumentTagFieldPositionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postGetDocumentTagFieldPositionWithHttpInfo($content_type, $get_document_tag_field_position_request = null)
    {
        $request = $this->postGetDocumentTagFieldPositionRequest($content_type, $get_document_tag_field_position_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\SigniFlowConnect\Model\GetDocumentTagFieldPositionResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SigniFlowConnect\Model\GetDocumentTagFieldPositionResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SigniFlowConnect\Model\GetDocumentTagFieldPositionResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SigniFlowConnect\Model\GetDocumentTagFieldPositionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postGetDocumentTagFieldPositionAsync
     *
     * Get Document Tag Field Position
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldPositionRequest $get_document_tag_field_position_request ##### Get Document Tag Field Position Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGetDocumentTagFieldPositionAsync($content_type, $get_document_tag_field_position_request = null)
    {
        return $this->postGetDocumentTagFieldPositionAsyncWithHttpInfo($content_type, $get_document_tag_field_position_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postGetDocumentTagFieldPositionAsyncWithHttpInfo
     *
     * Get Document Tag Field Position
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldPositionRequest $get_document_tag_field_position_request ##### Get Document Tag Field Position Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGetDocumentTagFieldPositionAsyncWithHttpInfo($content_type, $get_document_tag_field_position_request = null)
    {
        $returnType = '\SigniFlowConnect\Model\GetDocumentTagFieldPositionResponse';
        $request = $this->postGetDocumentTagFieldPositionRequest($content_type, $get_document_tag_field_position_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postGetDocumentTagFieldPosition'
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetDocumentTagFieldPositionRequest $get_document_tag_field_position_request ##### Get Document Tag Field Position Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postGetDocumentTagFieldPositionRequest($content_type, $get_document_tag_field_position_request = null)
    {
        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling postGetDocumentTagFieldPosition'
            );
        }

        $resourcePath = '/GetDocumentTagFieldPosition';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($get_document_tag_field_position_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($get_document_tag_field_position_request));
            } else {
                $httpBody = $get_document_tag_field_position_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postGetPrepperTemplate
     *
     * Get Prepper Template
     *
     * @param  string $content_type content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateRequest $get_prepper_template_request ##### Get Prepper Template Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SigniFlowConnect\Model\GetPrepperTemplateResponse
     */
    public function postGetPrepperTemplate($content_type, $get_prepper_template_request = null)
    {
        list($response) = $this->postGetPrepperTemplateWithHttpInfo($content_type, $get_prepper_template_request);
        return $response;
    }

    /**
     * Operation postGetPrepperTemplateWithHttpInfo
     *
     * Get Prepper Template
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateRequest $get_prepper_template_request ##### Get Prepper Template Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SigniFlowConnect\Model\GetPrepperTemplateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postGetPrepperTemplateWithHttpInfo($content_type, $get_prepper_template_request = null)
    {
        $request = $this->postGetPrepperTemplateRequest($content_type, $get_prepper_template_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\SigniFlowConnect\Model\GetPrepperTemplateResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SigniFlowConnect\Model\GetPrepperTemplateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SigniFlowConnect\Model\GetPrepperTemplateResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SigniFlowConnect\Model\GetPrepperTemplateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postGetPrepperTemplateAsync
     *
     * Get Prepper Template
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateRequest $get_prepper_template_request ##### Get Prepper Template Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGetPrepperTemplateAsync($content_type, $get_prepper_template_request = null)
    {
        return $this->postGetPrepperTemplateAsyncWithHttpInfo($content_type, $get_prepper_template_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postGetPrepperTemplateAsyncWithHttpInfo
     *
     * Get Prepper Template
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateRequest $get_prepper_template_request ##### Get Prepper Template Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGetPrepperTemplateAsyncWithHttpInfo($content_type, $get_prepper_template_request = null)
    {
        $returnType = '\SigniFlowConnect\Model\GetPrepperTemplateResponse';
        $request = $this->postGetPrepperTemplateRequest($content_type, $get_prepper_template_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postGetPrepperTemplate'
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateRequest $get_prepper_template_request ##### Get Prepper Template Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postGetPrepperTemplateRequest($content_type, $get_prepper_template_request = null)
    {
        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling postGetPrepperTemplate'
            );
        }

        $resourcePath = '/GetPrepperTemplate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($get_prepper_template_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($get_prepper_template_request));
            } else {
                $httpBody = $get_prepper_template_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postGetPrepperTemplateList
     *
     * Get Prepper Template List
     *
     * @param  string $content_type content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateListRequest $get_prepper_template_list_request ##### Get Prepper Template List Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SigniFlowConnect\Model\GetPrepperTemplateListResponse
     */
    public function postGetPrepperTemplateList($content_type, $get_prepper_template_list_request = null)
    {
        list($response) = $this->postGetPrepperTemplateListWithHttpInfo($content_type, $get_prepper_template_list_request);
        return $response;
    }

    /**
     * Operation postGetPrepperTemplateListWithHttpInfo
     *
     * Get Prepper Template List
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateListRequest $get_prepper_template_list_request ##### Get Prepper Template List Request Model (optional)
     *
     * @throws \SigniFlowConnect\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SigniFlowConnect\Model\GetPrepperTemplateListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function postGetPrepperTemplateListWithHttpInfo($content_type, $get_prepper_template_list_request = null)
    {
        $request = $this->postGetPrepperTemplateListRequest($content_type, $get_prepper_template_list_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\SigniFlowConnect\Model\GetPrepperTemplateListResponse' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SigniFlowConnect\Model\GetPrepperTemplateListResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SigniFlowConnect\Model\GetPrepperTemplateListResponse';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SigniFlowConnect\Model\GetPrepperTemplateListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postGetPrepperTemplateListAsync
     *
     * Get Prepper Template List
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateListRequest $get_prepper_template_list_request ##### Get Prepper Template List Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGetPrepperTemplateListAsync($content_type, $get_prepper_template_list_request = null)
    {
        return $this->postGetPrepperTemplateListAsyncWithHttpInfo($content_type, $get_prepper_template_list_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postGetPrepperTemplateListAsyncWithHttpInfo
     *
     * Get Prepper Template List
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateListRequest $get_prepper_template_list_request ##### Get Prepper Template List Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGetPrepperTemplateListAsyncWithHttpInfo($content_type, $get_prepper_template_list_request = null)
    {
        $returnType = '\SigniFlowConnect\Model\GetPrepperTemplateListResponse';
        $request = $this->postGetPrepperTemplateListRequest($content_type, $get_prepper_template_list_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postGetPrepperTemplateList'
     *
     * @param  string $content_type (required)
     * @param  \SigniFlowConnect\Model\GetPrepperTemplateListRequest $get_prepper_template_list_request ##### Get Prepper Template List Request Model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postGetPrepperTemplateListRequest($content_type, $get_prepper_template_list_request = null)
    {
        // verify the required parameter 'content_type' is set
        if ($content_type === null || (is_array($content_type) && count($content_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $content_type when calling postGetPrepperTemplateList'
            );
        }

        $resourcePath = '/GetPrepperTemplateList';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($get_prepper_template_list_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($get_prepper_template_list_request));
            } else {
                $httpBody = $get_prepper_template_list_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
