<?php
/**
 * CreateWorkflowRequest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SigniFlowConnect\Model;

use \ArrayAccess;
use \SigniFlowConnect\ObjectSerializer;

/**
 * CreateWorkflowRequest Class Doc Comment
 *
 * @category Class
 * @description #### The request sent to create a document workflow.
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class CreateWorkflowRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateWorkflowRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'additional_data_field' => 'string',
        'auto_expire_field' => '\SigniFlowConnect\Model\AutoExpire',
        'auto_remind_field' => '\SigniFlowConnect\Model\AutoRemind',
        'doc_field' => 'string',
        'doc_name_field' => 'string',
        'due_date_field' => '\DateTime',
        'extension_field' => '\SigniFlowConnect\Model\DocExtension',
        'message_field' => 'string',
        'priority_field' => '\SigniFlowConnect\Model\Priority',
        'sla_field' => 'int',
        'token_field' => '\SigniFlowConnect\Model\TokenField'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'additional_data_field' => null,
        'auto_expire_field' => null,
        'auto_remind_field' => null,
        'doc_field' => null,
        'doc_name_field' => null,
        'due_date_field' => 'date-time',
        'extension_field' => null,
        'message_field' => null,
        'priority_field' => null,
        'sla_field' => null,
        'token_field' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'additional_data_field' => 'AdditionalDataField',
        'auto_expire_field' => 'AutoExpireField',
        'auto_remind_field' => 'AutoRemindField',
        'doc_field' => 'DocField',
        'doc_name_field' => 'DocNameField',
        'due_date_field' => 'DueDateField',
        'extension_field' => 'ExtensionField',
        'message_field' => 'MessageField',
        'priority_field' => 'PriorityField',
        'sla_field' => 'SLAField',
        'token_field' => 'TokenField'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'additional_data_field' => 'setAdditionalDataField',
        'auto_expire_field' => 'setAutoExpireField',
        'auto_remind_field' => 'setAutoRemindField',
        'doc_field' => 'setDocField',
        'doc_name_field' => 'setDocNameField',
        'due_date_field' => 'setDueDateField',
        'extension_field' => 'setExtensionField',
        'message_field' => 'setMessageField',
        'priority_field' => 'setPriorityField',
        'sla_field' => 'setSlaField',
        'token_field' => 'setTokenField'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'additional_data_field' => 'getAdditionalDataField',
        'auto_expire_field' => 'getAutoExpireField',
        'auto_remind_field' => 'getAutoRemindField',
        'doc_field' => 'getDocField',
        'doc_name_field' => 'getDocNameField',
        'due_date_field' => 'getDueDateField',
        'extension_field' => 'getExtensionField',
        'message_field' => 'getMessageField',
        'priority_field' => 'getPriorityField',
        'sla_field' => 'getSlaField',
        'token_field' => 'getTokenField'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['additional_data_field'] = $data['additional_data_field'] ?? null;
        $this->container['auto_expire_field'] = $data['auto_expire_field'] ?? null;
        $this->container['auto_remind_field'] = $data['auto_remind_field'] ?? null;
        $this->container['doc_field'] = $data['doc_field'] ?? null;
        $this->container['doc_name_field'] = $data['doc_name_field'] ?? null;
        $this->container['due_date_field'] = $data['due_date_field'] ?? null;
        $this->container['extension_field'] = $data['extension_field'] ?? null;
        $this->container['message_field'] = $data['message_field'] ?? null;
        $this->container['priority_field'] = $data['priority_field'] ?? null;
        $this->container['sla_field'] = $data['sla_field'] ?? 0;
        $this->container['token_field'] = $data['token_field'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['additional_data_field'] === null) {
            $invalidProperties[] = "'additional_data_field' can't be null";
        }
        if ($this->container['auto_expire_field'] === null) {
            $invalidProperties[] = "'auto_expire_field' can't be null";
        }
        if ($this->container['auto_remind_field'] === null) {
            $invalidProperties[] = "'auto_remind_field' can't be null";
        }
        if ($this->container['doc_field'] === null) {
            $invalidProperties[] = "'doc_field' can't be null";
        }
        if ($this->container['doc_name_field'] === null) {
            $invalidProperties[] = "'doc_name_field' can't be null";
        }
        if ($this->container['extension_field'] === null) {
            $invalidProperties[] = "'extension_field' can't be null";
        }
        if ($this->container['message_field'] === null) {
            $invalidProperties[] = "'message_field' can't be null";
        }
        if ($this->container['priority_field'] === null) {
            $invalidProperties[] = "'priority_field' can't be null";
        }
        if ($this->container['sla_field'] === null) {
            $invalidProperties[] = "'sla_field' can't be null";
        }
        if (($this->container['sla_field'] > 0)) {
            $invalidProperties[] = "invalid value for 'sla_field', must be smaller than or equal to 0.";
        }

        if (($this->container['sla_field'] < 0)) {
            $invalidProperties[] = "invalid value for 'sla_field', must be bigger than or equal to 0.";
        }

        if ($this->container['token_field'] === null) {
            $invalidProperties[] = "'token_field' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets additional_data_field
     *
     * @return string
     */
    public function getAdditionalDataField()
    {
        return $this->container['additional_data_field'];
    }

    /**
     * Sets additional_data_field
     *
     * @param string $additional_data_field Sets additional data to be embedded in PDF Meta.
     *
     * @return self
     */
    public function setAdditionalDataField($additional_data_field)
    {
        $this->container['additional_data_field'] = $additional_data_field;

        return $this;
    }

    /**
     * Gets auto_expire_field
     *
     * @return \SigniFlowConnect\Model\AutoExpire
     */
    public function getAutoExpireField()
    {
        return $this->container['auto_expire_field'];
    }

    /**
     * Sets auto_expire_field
     *
     * @param \SigniFlowConnect\Model\AutoExpire $auto_expire_field auto_expire_field
     *
     * @return self
     */
    public function setAutoExpireField($auto_expire_field)
    {
        $this->container['auto_expire_field'] = $auto_expire_field;

        return $this;
    }

    /**
     * Gets auto_remind_field
     *
     * @return \SigniFlowConnect\Model\AutoRemind
     */
    public function getAutoRemindField()
    {
        return $this->container['auto_remind_field'];
    }

    /**
     * Sets auto_remind_field
     *
     * @param \SigniFlowConnect\Model\AutoRemind $auto_remind_field auto_remind_field
     *
     * @return self
     */
    public function setAutoRemindField($auto_remind_field)
    {
        $this->container['auto_remind_field'] = $auto_remind_field;

        return $this;
    }

    /**
     * Gets doc_field
     *
     * @return string
     */
    public function getDocField()
    {
        return $this->container['doc_field'];
    }

    /**
     * Sets doc_field
     *
     * @param string $doc_field Base64 Encoded String of document
     *
     * @return self
     */
    public function setDocField($doc_field)
    {
        $this->container['doc_field'] = $doc_field;

        return $this;
    }

    /**
     * Gets doc_name_field
     *
     * @return string
     */
    public function getDocNameField()
    {
        return $this->container['doc_name_field'];
    }

    /**
     * Sets doc_name_field
     *
     * @param string $doc_name_field Name of document to display in SigniFlow
     *
     * @return self
     */
    public function setDocNameField($doc_name_field)
    {
        $this->container['doc_name_field'] = $doc_name_field;

        return $this;
    }

    /**
     * Gets due_date_field
     *
     * @return \DateTime|null
     */
    public function getDueDateField()
    {
        return $this->container['due_date_field'];
    }

    /**
     * Sets due_date_field
     *
     * @param \DateTime|null $due_date_field Due date for the document, use in conjunction with Auto Expire.
     *
     * @return self
     */
    public function setDueDateField($due_date_field)
    {
        $this->container['due_date_field'] = $due_date_field;

        return $this;
    }

    /**
     * Gets extension_field
     *
     * @return \SigniFlowConnect\Model\DocExtension
     */
    public function getExtensionField()
    {
        return $this->container['extension_field'];
    }

    /**
     * Sets extension_field
     *
     * @param \SigniFlowConnect\Model\DocExtension $extension_field extension_field
     *
     * @return self
     */
    public function setExtensionField($extension_field)
    {
        $this->container['extension_field'] = $extension_field;

        return $this;
    }

    /**
     * Gets message_field
     *
     * @return string
     */
    public function getMessageField()
    {
        return $this->container['message_field'];
    }

    /**
     * Sets message_field
     *
     * @param string $message_field Custom message to display to participants
     *
     * @return self
     */
    public function setMessageField($message_field)
    {
        $this->container['message_field'] = $message_field;

        return $this;
    }

    /**
     * Gets priority_field
     *
     * @return \SigniFlowConnect\Model\Priority
     */
    public function getPriorityField()
    {
        return $this->container['priority_field'];
    }

    /**
     * Sets priority_field
     *
     * @param \SigniFlowConnect\Model\Priority $priority_field priority_field
     *
     * @return self
     */
    public function setPriorityField($priority_field)
    {
        $this->container['priority_field'] = $priority_field;

        return $this;
    }

    /**
     * Gets sla_field
     *
     * @return int
     */
    public function getSlaField()
    {
        return $this->container['sla_field'];
    }

    /**
     * Sets sla_field
     *
     * @param int $sla_field Deprecated field, Pass 0
     *
     * @return self
     */
    public function setSlaField($sla_field)
    {

        if (($sla_field > 0)) {
            throw new \InvalidArgumentException('invalid value for $sla_field when calling CreateWorkflowRequest., must be smaller than or equal to 0.');
        }
        if (($sla_field < 0)) {
            throw new \InvalidArgumentException('invalid value for $sla_field when calling CreateWorkflowRequest., must be bigger than or equal to 0.');
        }

        $this->container['sla_field'] = $sla_field;

        return $this;
    }

    /**
     * Gets token_field
     *
     * @return \SigniFlowConnect\Model\TokenField
     */
    public function getTokenField()
    {
        return $this->container['token_field'];
    }

    /**
     * Sets token_field
     *
     * @param \SigniFlowConnect\Model\TokenField $token_field token_field
     *
     * @return self
     */
    public function setTokenField($token_field)
    {
        $this->container['token_field'] = $token_field;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


