<?php
/**
 * GetPrepperTemplateListResponseTemplateInformationValuesField
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SigniFlowConnect\Model;

use \ArrayAccess;
use \SigniFlowConnect\ObjectSerializer;

/**
 * GetPrepperTemplateListResponseTemplateInformationValuesField Class Doc Comment
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class GetPrepperTemplateListResponseTemplateInformationValuesField implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetPrepperTemplateListResponse_TemplateInformationValuesField';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name_field' => 'string',
        'prepper_template_id_field' => 'float',
        'template_description_field' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name_field' => null,
        'prepper_template_id_field' => null,
        'template_description_field' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name_field' => 'NameField',
        'prepper_template_id_field' => 'PrepperTemplateIDField',
        'template_description_field' => 'TemplateDescriptionField'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name_field' => 'setNameField',
        'prepper_template_id_field' => 'setPrepperTemplateIdField',
        'template_description_field' => 'setTemplateDescriptionField'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name_field' => 'getNameField',
        'prepper_template_id_field' => 'getPrepperTemplateIdField',
        'template_description_field' => 'getTemplateDescriptionField'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name_field'] = $data['name_field'] ?? null;
        $this->container['prepper_template_id_field'] = $data['prepper_template_id_field'] ?? null;
        $this->container['template_description_field'] = $data['template_description_field'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name_field'] === null) {
            $invalidProperties[] = "'name_field' can't be null";
        }
        if ((mb_strlen($this->container['name_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'name_field', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['prepper_template_id_field'] === null) {
            $invalidProperties[] = "'prepper_template_id_field' can't be null";
        }
        if ($this->container['template_description_field'] === null) {
            $invalidProperties[] = "'template_description_field' can't be null";
        }
        if ((mb_strlen($this->container['template_description_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'template_description_field', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name_field
     *
     * @return string
     */
    public function getNameField()
    {
        return $this->container['name_field'];
    }

    /**
     * Sets name_field
     *
     * @param string $name_field name_field
     *
     * @return self
     */
    public function setNameField($name_field)
    {

        if ((mb_strlen($name_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name_field when calling GetPrepperTemplateListResponseTemplateInformationValuesField., must be bigger than or equal to 1.');
        }

        $this->container['name_field'] = $name_field;

        return $this;
    }

    /**
     * Gets prepper_template_id_field
     *
     * @return float
     */
    public function getPrepperTemplateIdField()
    {
        return $this->container['prepper_template_id_field'];
    }

    /**
     * Sets prepper_template_id_field
     *
     * @param float $prepper_template_id_field prepper_template_id_field
     *
     * @return self
     */
    public function setPrepperTemplateIdField($prepper_template_id_field)
    {
        $this->container['prepper_template_id_field'] = $prepper_template_id_field;

        return $this;
    }

    /**
     * Gets template_description_field
     *
     * @return string
     */
    public function getTemplateDescriptionField()
    {
        return $this->container['template_description_field'];
    }

    /**
     * Sets template_description_field
     *
     * @param string $template_description_field Template description.
     *
     * @return self
     */
    public function setTemplateDescriptionField($template_description_field)
    {

        if ((mb_strlen($template_description_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $template_description_field when calling GetPrepperTemplateListResponseTemplateInformationValuesField., must be bigger than or equal to 1.');
        }

        $this->container['template_description_field'] = $template_description_field;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


