<?php
/**
 * SharePortfolioNoEmailRequest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SigniFlowConnect\Model;

use \ArrayAccess;
use \SigniFlowConnect\ObjectSerializer;

/**
 * SharePortfolioNoEmailRequest Class Doc Comment
 *
 * @category Class
 * @description #### The request sent when a user wants to share a portfolio but does not want an email to be sent.
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class SharePortfolioNoEmailRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SharePortfolio_No_EmailRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'access_level_field' => 'float',
        'portfolio_id_field' => 'string',
        'share_option_field' => 'float',
        'token_field' => '\SigniFlowConnect\Model\TokenField',
        'unique_id_field' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'access_level_field' => null,
        'portfolio_id_field' => null,
        'share_option_field' => null,
        'token_field' => null,
        'unique_id_field' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'access_level_field' => 'AccessLevelField',
        'portfolio_id_field' => 'PortfolioIDField',
        'share_option_field' => 'ShareOptionField',
        'token_field' => 'TokenField',
        'unique_id_field' => 'UniqueIDField'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'access_level_field' => 'setAccessLevelField',
        'portfolio_id_field' => 'setPortfolioIdField',
        'share_option_field' => 'setShareOptionField',
        'token_field' => 'setTokenField',
        'unique_id_field' => 'setUniqueIdField'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'access_level_field' => 'getAccessLevelField',
        'portfolio_id_field' => 'getPortfolioIdField',
        'share_option_field' => 'getShareOptionField',
        'token_field' => 'getTokenField',
        'unique_id_field' => 'getUniqueIdField'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['access_level_field'] = $data['access_level_field'] ?? null;
        $this->container['portfolio_id_field'] = $data['portfolio_id_field'] ?? null;
        $this->container['share_option_field'] = $data['share_option_field'] ?? null;
        $this->container['token_field'] = $data['token_field'] ?? null;
        $this->container['unique_id_field'] = $data['unique_id_field'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['access_level_field'] === null) {
            $invalidProperties[] = "'access_level_field' can't be null";
        }
        if ($this->container['portfolio_id_field'] === null) {
            $invalidProperties[] = "'portfolio_id_field' can't be null";
        }
        if ((mb_strlen($this->container['portfolio_id_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'portfolio_id_field', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['share_option_field'] === null) {
            $invalidProperties[] = "'share_option_field' can't be null";
        }
        if ($this->container['token_field'] === null) {
            $invalidProperties[] = "'token_field' can't be null";
        }
        if ($this->container['unique_id_field'] === null) {
            $invalidProperties[] = "'unique_id_field' can't be null";
        }
        if ((mb_strlen($this->container['unique_id_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'unique_id_field', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets access_level_field
     *
     * @return float
     */
    public function getAccessLevelField()
    {
        return $this->container['access_level_field'];
    }

    /**
     * Sets access_level_field
     *
     * @param float $access_level_field access_level_field
     *
     * @return self
     */
    public function setAccessLevelField($access_level_field)
    {
        $this->container['access_level_field'] = $access_level_field;

        return $this;
    }

    /**
     * Gets portfolio_id_field
     *
     * @return string
     */
    public function getPortfolioIdField()
    {
        return $this->container['portfolio_id_field'];
    }

    /**
     * Sets portfolio_id_field
     *
     * @param string $portfolio_id_field portfolio_id_field
     *
     * @return self
     */
    public function setPortfolioIdField($portfolio_id_field)
    {

        if ((mb_strlen($portfolio_id_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $portfolio_id_field when calling SharePortfolioNoEmailRequest., must be bigger than or equal to 1.');
        }

        $this->container['portfolio_id_field'] = $portfolio_id_field;

        return $this;
    }

    /**
     * Gets share_option_field
     *
     * @return float
     */
    public function getShareOptionField()
    {
        return $this->container['share_option_field'];
    }

    /**
     * Sets share_option_field
     *
     * @param float $share_option_field share_option_field
     *
     * @return self
     */
    public function setShareOptionField($share_option_field)
    {
        $this->container['share_option_field'] = $share_option_field;

        return $this;
    }

    /**
     * Gets token_field
     *
     * @return \SigniFlowConnect\Model\TokenField
     */
    public function getTokenField()
    {
        return $this->container['token_field'];
    }

    /**
     * Sets token_field
     *
     * @param \SigniFlowConnect\Model\TokenField $token_field token_field
     *
     * @return self
     */
    public function setTokenField($token_field)
    {
        $this->container['token_field'] = $token_field;

        return $this;
    }

    /**
     * Gets unique_id_field
     *
     * @return string
     */
    public function getUniqueIdField()
    {
        return $this->container['unique_id_field'];
    }

    /**
     * Sets unique_id_field
     *
     * @param string $unique_id_field unique_id_field
     *
     * @return self
     */
    public function setUniqueIdField($unique_id_field)
    {

        if ((mb_strlen($unique_id_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $unique_id_field when calling SharePortfolioNoEmailRequest., must be bigger than or equal to 1.');
        }

        $this->container['unique_id_field'] = $unique_id_field;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


