<?php
/**
 * WorkflowSignRequest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SigniFlowConnect\Model;

use \ArrayAccess;
use \SigniFlowConnect\ObjectSerializer;

/**
 * WorkflowSignRequest Class Doc Comment
 *
 * @category Class
 * @description #### This request is sent when a document workflow needs to be signed.
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class WorkflowSignRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WorkflowSignRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'doc_id_field' => 'string',
        'latitude_field' => 'string',
        'login_password_field' => 'string',
        'login_user_name_field' => 'string',
        'longitude_field' => 'string',
        'sign_reason_field' => 'string',
        'time_zone_offset_field' => 'float',
        'token_field' => '\SigniFlowConnect\Model\TokenField'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'doc_id_field' => null,
        'latitude_field' => null,
        'login_password_field' => 'password',
        'login_user_name_field' => null,
        'longitude_field' => null,
        'sign_reason_field' => null,
        'time_zone_offset_field' => null,
        'token_field' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'doc_id_field' => 'DocIDField',
        'latitude_field' => 'LatitudeField',
        'login_password_field' => 'LoginPasswordField',
        'login_user_name_field' => 'LoginUserNameField',
        'longitude_field' => 'LongitudeField',
        'sign_reason_field' => 'SignReasonField',
        'time_zone_offset_field' => 'TimeZoneOffsetField',
        'token_field' => 'TokenField'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'doc_id_field' => 'setDocIdField',
        'latitude_field' => 'setLatitudeField',
        'login_password_field' => 'setLoginPasswordField',
        'login_user_name_field' => 'setLoginUserNameField',
        'longitude_field' => 'setLongitudeField',
        'sign_reason_field' => 'setSignReasonField',
        'time_zone_offset_field' => 'setTimeZoneOffsetField',
        'token_field' => 'setTokenField'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'doc_id_field' => 'getDocIdField',
        'latitude_field' => 'getLatitudeField',
        'login_password_field' => 'getLoginPasswordField',
        'login_user_name_field' => 'getLoginUserNameField',
        'longitude_field' => 'getLongitudeField',
        'sign_reason_field' => 'getSignReasonField',
        'time_zone_offset_field' => 'getTimeZoneOffsetField',
        'token_field' => 'getTokenField'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['doc_id_field'] = $data['doc_id_field'] ?? null;
        $this->container['latitude_field'] = $data['latitude_field'] ?? null;
        $this->container['login_password_field'] = $data['login_password_field'] ?? null;
        $this->container['login_user_name_field'] = $data['login_user_name_field'] ?? null;
        $this->container['longitude_field'] = $data['longitude_field'] ?? null;
        $this->container['sign_reason_field'] = $data['sign_reason_field'] ?? null;
        $this->container['time_zone_offset_field'] = $data['time_zone_offset_field'] ?? null;
        $this->container['token_field'] = $data['token_field'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['doc_id_field'] === null) {
            $invalidProperties[] = "'doc_id_field' can't be null";
        }
        if ((mb_strlen($this->container['doc_id_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'doc_id_field', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['latitude_field'] === null) {
            $invalidProperties[] = "'latitude_field' can't be null";
        }
        if ((mb_strlen($this->container['latitude_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'latitude_field', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['login_password_field'] === null) {
            $invalidProperties[] = "'login_password_field' can't be null";
        }
        if ((mb_strlen($this->container['login_password_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'login_password_field', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['login_user_name_field'] === null) {
            $invalidProperties[] = "'login_user_name_field' can't be null";
        }
        if ((mb_strlen($this->container['login_user_name_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'login_user_name_field', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['longitude_field'] === null) {
            $invalidProperties[] = "'longitude_field' can't be null";
        }
        if ((mb_strlen($this->container['longitude_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'longitude_field', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['sign_reason_field'] === null) {
            $invalidProperties[] = "'sign_reason_field' can't be null";
        }
        if ((mb_strlen($this->container['sign_reason_field']) < 1)) {
            $invalidProperties[] = "invalid value for 'sign_reason_field', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['time_zone_offset_field'] === null) {
            $invalidProperties[] = "'time_zone_offset_field' can't be null";
        }
        if ($this->container['token_field'] === null) {
            $invalidProperties[] = "'token_field' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets doc_id_field
     *
     * @return string
     */
    public function getDocIdField()
    {
        return $this->container['doc_id_field'];
    }

    /**
     * Sets doc_id_field
     *
     * @param string $doc_id_field doc_id_field
     *
     * @return self
     */
    public function setDocIdField($doc_id_field)
    {

        if ((mb_strlen($doc_id_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $doc_id_field when calling WorkflowSignRequest., must be bigger than or equal to 1.');
        }

        $this->container['doc_id_field'] = $doc_id_field;

        return $this;
    }

    /**
     * Gets latitude_field
     *
     * @return string
     */
    public function getLatitudeField()
    {
        return $this->container['latitude_field'];
    }

    /**
     * Sets latitude_field
     *
     * @param string $latitude_field latitude_field
     *
     * @return self
     */
    public function setLatitudeField($latitude_field)
    {

        if ((mb_strlen($latitude_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $latitude_field when calling WorkflowSignRequest., must be bigger than or equal to 1.');
        }

        $this->container['latitude_field'] = $latitude_field;

        return $this;
    }

    /**
     * Gets login_password_field
     *
     * @return string
     */
    public function getLoginPasswordField()
    {
        return $this->container['login_password_field'];
    }

    /**
     * Sets login_password_field
     *
     * @param string $login_password_field login_password_field
     *
     * @return self
     */
    public function setLoginPasswordField($login_password_field)
    {

        if ((mb_strlen($login_password_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $login_password_field when calling WorkflowSignRequest., must be bigger than or equal to 1.');
        }

        $this->container['login_password_field'] = $login_password_field;

        return $this;
    }

    /**
     * Gets login_user_name_field
     *
     * @return string
     */
    public function getLoginUserNameField()
    {
        return $this->container['login_user_name_field'];
    }

    /**
     * Sets login_user_name_field
     *
     * @param string $login_user_name_field login_user_name_field
     *
     * @return self
     */
    public function setLoginUserNameField($login_user_name_field)
    {

        if ((mb_strlen($login_user_name_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $login_user_name_field when calling WorkflowSignRequest., must be bigger than or equal to 1.');
        }

        $this->container['login_user_name_field'] = $login_user_name_field;

        return $this;
    }

    /**
     * Gets longitude_field
     *
     * @return string
     */
    public function getLongitudeField()
    {
        return $this->container['longitude_field'];
    }

    /**
     * Sets longitude_field
     *
     * @param string $longitude_field longitude_field
     *
     * @return self
     */
    public function setLongitudeField($longitude_field)
    {

        if ((mb_strlen($longitude_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $longitude_field when calling WorkflowSignRequest., must be bigger than or equal to 1.');
        }

        $this->container['longitude_field'] = $longitude_field;

        return $this;
    }

    /**
     * Gets sign_reason_field
     *
     * @return string
     */
    public function getSignReasonField()
    {
        return $this->container['sign_reason_field'];
    }

    /**
     * Sets sign_reason_field
     *
     * @param string $sign_reason_field sign_reason_field
     *
     * @return self
     */
    public function setSignReasonField($sign_reason_field)
    {

        if ((mb_strlen($sign_reason_field) < 1)) {
            throw new \InvalidArgumentException('invalid length for $sign_reason_field when calling WorkflowSignRequest., must be bigger than or equal to 1.');
        }

        $this->container['sign_reason_field'] = $sign_reason_field;

        return $this;
    }

    /**
     * Gets time_zone_offset_field
     *
     * @return float
     */
    public function getTimeZoneOffsetField()
    {
        return $this->container['time_zone_offset_field'];
    }

    /**
     * Sets time_zone_offset_field
     *
     * @param float $time_zone_offset_field time_zone_offset_field
     *
     * @return self
     */
    public function setTimeZoneOffsetField($time_zone_offset_field)
    {
        $this->container['time_zone_offset_field'] = $time_zone_offset_field;

        return $this;
    }

    /**
     * Gets token_field
     *
     * @return \SigniFlowConnect\Model\TokenField
     */
    public function getTokenField()
    {
        return $this->container['token_field'];
    }

    /**
     * Sets token_field
     *
     * @param \SigniFlowConnect\Model\TokenField $token_field token_field
     *
     * @return self
     */
    public function setTokenField($token_field)
    {
        $this->container['token_field'] = $token_field;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


