<?php
/**
 * AddWokflowStepV2ResponseFlowStepsFieldTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SigniFlowConnect\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AddWokflowStepV2ResponseFlowStepsFieldTest Class Doc Comment
 *
 * @category    Class
 * @description AddWokflowStepV2ResponseFlowStepsField
 * @package     SigniFlowConnect
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddWokflowStepV2ResponseFlowStepsFieldTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AddWokflowStepV2ResponseFlowStepsField"
     */
    public function testAddWokflowStepV2ResponseFlowStepsField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "action_field"
     */
    public function testPropertyActionField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email_field"
     */
    public function testPropertyEmailField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "flow_id_field"
     */
    public function testPropertyFlowIdField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
