<?php
/**
 * DocPrepperAddAdvancedFieldsRequestFieldInfoListFieldTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SigniFlowConnect\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DocPrepperAddAdvancedFieldsRequestFieldInfoListFieldTest Class Doc Comment
 *
 * @category    Class
 * @description DocPrepperAddAdvancedFieldsRequestFieldInfoListField
 * @package     SigniFlowConnect
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DocPrepperAddAdvancedFieldsRequestFieldInfoListFieldTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DocPrepperAddAdvancedFieldsRequestFieldInfoListField"
     */
    public function testDocPrepperAddAdvancedFieldsRequestFieldInfoListField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "advanced_field_type_field"
     */
    public function testPropertyAdvancedFieldTypeField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "doc_id_field"
     */
    public function testPropertyDocIdField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "field_options_list_field"
     */
    public function testPropertyFieldOptionsListField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "flow_id_field"
     */
    public function testPropertyFlowIdField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "font_family_field"
     */
    public function testPropertyFontFamilyField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "font_size_field"
     */
    public function testPropertyFontSizeField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "height_field"
     */
    public function testPropertyHeightField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "width_field"
     */
    public function testPropertyWidthField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "link_to_field"
     */
    public function testPropertyLinkToField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name_field"
     */
    public function testPropertyNameField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "page_number_field"
     */
    public function testPropertyPageNumberField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "searchable_field"
     */
    public function testPropertySearchableField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "user_email_field"
     */
    public function testPropertyUserEmailField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "value_field"
     */
    public function testPropertyValueField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "x_coordinate_field"
     */
    public function testPropertyXCoordinateField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "y_coordinate_field"
     */
    public function testPropertyYCoordinateField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
