<?php
/**
 * FullWorkflowRequestTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SigniFlowConnect\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FullWorkflowRequestTest Class Doc Comment
 *
 * @category    Class
 * @description #### Request a fullworkflow of a document.
 * @package     SigniFlowConnect
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FullWorkflowRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FullWorkflowRequest"
     */
    public function testFullWorkflowRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additional_data_field"
     */
    public function testPropertyAdditionalDataField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "auto_remind_field"
     */
    public function testPropertyAutoRemindField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "custom_message_field"
     */
    public function testPropertyCustomMessageField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "doc_field"
     */
    public function testPropertyDocField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "doc_name_field"
     */
    public function testPropertyDocNameField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "due_date_field"
     */
    public function testPropertyDueDateField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "extension_field"
     */
    public function testPropertyExtensionField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "flatten_document_field"
     */
    public function testPropertyFlattenDocumentField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "keep_content_security_field"
     */
    public function testPropertyKeepContentSecurityField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "keep_custom_properties_field"
     */
    public function testPropertyKeepCustomPropertiesField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "keep_xmp_metadata_field"
     */
    public function testPropertyKeepXmpMetadataField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "portfolio_information_field"
     */
    public function testPropertyPortfolioInformationField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "priority_field"
     */
    public function testPropertyPriorityField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sla_field"
     */
    public function testPropertySlaField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "send_first_email_field"
     */
    public function testPropertySendFirstEmailField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "send_workflow_emails_field"
     */
    public function testPropertySendWorkflowEmailsField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "token_field"
     */
    public function testPropertyTokenField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "workflow_users_list_field"
     */
    public function testPropertyWorkflowUsersListField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
