<?php
/**
 * SetDocumentOrderResponseTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  SigniFlowConnect
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SigniFlowConnect\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SetDocumentOrderResponseTest Class Doc Comment
 *
 * @category    Class
 * @description #### The response returned when the document order for signing is set.
 * @package     SigniFlowConnect
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SetDocumentOrderResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SetDocumentOrderResponse"
     */
    public function testSetDocumentOrderResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "result_field"
     */
    public function testPropertyResultField()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
